### ISSUE TITLE
fine-tuning from a BERT weight

### ISSUE THREAD

**Issue by azamatolegen** [howardhsu/BERT-for-RRC-ABSA#10]
Greate article!

I am trying to reproduce results, when i run this code

 `bash run_absa.sh ae rest_pt rest pt_ae 10 0`

it shows me 

using cuda0

and nothing happens

What should I do?

**Comment by howardhsu** [comment]
we didn't print out error on logging. 

you can check or uncomment $OUTPUT_DIR/train_log.txt

**Comment by cjw245929674** [comment]
I'm sorry to bother you. My computer cannot open the URL of the dataset. Can you send me a copy? My email is 245929674@qq.com thank you very much !!!

**Comment by howardhsu** [comment]
resolved in another issue.
