### ISSUE TITLE
Feedback for missing Instructions

### ISSUE THREAD

**Issue by gagan94** [howardhsu/BERT-for-RRC-ABSA#11]
Since you had asked for feedback for missing instructions, hence writing this.

Can you please mentions the steps to evaluate the model on custom input with pretrained model weights ? It would be very helpful to implement and see the results.

**Comment by howardhsu** [comment]
what do you mean by custom input ? 
an interactive demo code ?
I had one before but my hard disk is burnt last month :-(

**Comment by gagan94** [comment]
Yes, an interactive demo code would have been very helpful.

If not, please do let us know the instructions on how to use trained model to do so ?

Right now, I have followed the instructions present to finetune and instead of running evaluation , I would like to check the model on my input. How can I do that ? How can I use the finetuned model ?

Thanks in Advance !

**Comment by cjw245929674** [comment]
I'm sorry to bother you. My computer cannot open the URL of the dataset. Can you send me a copy? My   email is 245929674@qq.com  thank you very much !!!

**Comment by howardhsu** [comment]
https://github.com/howardhsu/BERT-for-RRC-ABSA/blob/master/data/json_data.tar.gz

**Comment by howardhsu** [comment]
just have time to rewrite a demo code by chance: `src/demo_bert.py`. You can modify it for different purposes of pre-trained/ post-trained or end tasks.

**Comment by gagan94** [comment]
Thank you so much. Will try it out ! :)
