### ISSUE TITLE
where can i download the dataset?? i can not open the link. thank you

### ISSUE THREAD

**Issue by cjw245929674** [howardhsu/BERT-for-RRC-ABSA#12]

**Comment by cjw245929674** [comment]
if someone has the dataset ,would you please send me. my email is 245929674@qq.com  thank you very much  !!!

**Comment by howardhsu** [comment]
Sorry for putting things on google. 
You can check here.
https://github.com/howardhsu/BERT-for-RRC-ABSA/blob/master/data/json_data.tar.gz
