### ISSUE TITLE
a question about pt_model?

### ISSUE THREAD

**Issue by zhhhzhang** [howardhsu/BERT-for-RRC-ABSA#14]
i want to know what's the difference between laptop_pt_review and laptop_pt you have released?

**Comment by howardhsu** [comment]
laptop_pt_review is BERT-DK in paper using reviews only. laptop_pt (BERT-PT) is jointly trained from reviews and SQuAD.

**Comment by zhhhzhang** [comment]
i got it. thank you very much！



---Original---
