### ISSUE TITLE
Domain words out of vocabulary

### ISSUE THREAD

**Issue by wiz33** [howardhsu/BERT-for-RRC-ABSA#4]
Hi!

I found some [unused] tokens in your laptop domain data for post training, I've supposed they are specific domain words injected into the vocabulary, am I right? In case, is it possible to retrieve the list of those words somewhere?

Thanks!

**Comment by howardhsu** [comment]
I lost the code for original preprocessing of laptop reviews. But you can filter laptop reviews in Electronics of Amazon review datasets and see the vocabularies.
