### ISSUE TITLE
data preprocessing

### ISSUE THREAD

**Issue by foreverfc1994** [howardhsu/BERT-for-RRC-ABSA#5]
Take the liberty of asking, can you provide the code processing  Semsval data from XML to JSON ? I want to do some experiments on 14 and 15 years of restaurant data sets?

**Comment by filipealeixo** [comment]
+1 would also be interested in that code

**Comment by howardhsu** [comment]
The AE and ASC preprocessing are added. 
Note that AE is just for demo purpose.
The paper uses a conversion from [DE-CNN](https://github.com/howardhsu/DE-CNN).

**Comment by howardhsu** [comment]
We are going to release a preprocessing code base soon [here](https://github.com/howardhsu/ABSA_preprocessing), although it's not 100% compatible with old papers.
