### ISSUE TITLE
Also about the post-train models

### ISSUE THREAD

**Issue by zhaohe1995** [howardhsu/BERT-for-RRC-ABSA#8]
Can you also release the BERT-DK models, as is mentioned in your paper?
It will be very kind of you to provide the post-trained models which targeting at the specific domains!
![image](https://user-images.githubusercontent.com/13341661/64396244-97f7a200-d08f-11e9-90ad-c333cb8223af.png)

**Comment by howardhsu** [comment]
sure. we will.
