### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by nehas2603** [howardhsu/BERT-for-RRC-ABSA#9]
Kindly share the code for inference step for ae.

**Comment by howardhsu** [comment]
We are aiming for a newer version of this code base and hope to implement one in that version.

**Comment by pnageshkar** [comment]
Is this available now ?

**Comment by pnageshkar** [comment]
> We are aiming for a newer version of this code base and hope to implement one in that version.

Is this available now ? Could you please point me to it ? Thanks.

**Comment by ZohaibRamzan** [comment]
Is it available?
